module-template: ! "-----------------------------------------------------------------------------\n--
  |\n-- Module      :  MODULE_NAME\n-- Copyright   :  (c) 2014, Jakub Kozlowski\n--
  License     :  MIT\n--\n-- Maintainer  :  mail@jakub-kozlowski.com\n--\n-- \n-----------------------------------------------------------------------------\nmodule
  MODULE_NAME where\n"
extensions: {}
environment: ghc-7.8-unstable
cabal-file: thebook.cabal
hidden-packages: network-conduit
version: 1
extra-packages: ! 'Hackage: tasty-quickcheck 0.3.1

  Hackage: Decimal 0.3.1

  Hackage: exceptions 0.5

  Hackage: resourcet 1.1.0

  Hackage: streaming-commons 0.1.0.2

  Hackage: text-stream-decode 0.1.0.5

  Hackage: conduit 1.1.0

  Hackage: conduit-extra 1.1.0'
ghc-args:
- -Wall
- -fwarn-incomplete-patterns
excluded-modules: []
