language: haskell

before_install:
  - cabal install 'hpc-coveralls >= 0.1.2'
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=test,bench thebook-tests
